In [1]:
import pandas as pd
import numpy as np
import openpyxl
import seaborn as sb
import seaborn as sns
import matplotlib.pyplot as plt
import pickle
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder, OrdinalEncoder

#for classfication
from sklearn.ensemble import RandomForestClassifier

# for resampling 
from imblearn.over_sampling import RandomOverSampler

# for checking testing results
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('Energy data 1990 - 2020.csv')
df.head()

country  Year       Region  CO2 emissions from fuel combustion (MtCO2)  \
0  Algeria  1990  Arab States                                   52.981921   
1  Algeria  1991  Arab States                                   57.149971   
2  Algeria  1992  Arab States                                   57.262430   
3  Algeria  1993  Arab States                                   59.198702   
4  Algeria  1994  Arab States                                   56.347927   

   Average CO2 emission factor (tCO2/toe)  \
0                                2.387855   
1                                2.435026   
2                                2.383517   
3                                2.455335   
4                                2.424649   

   CO2 intensity at constant purchasing power parities (kCO2/$15p)  \
0                                           0.228889                 
1                                           0.249895                 
2                                           0.245959                 
3                                           0.259730                 
4                                           0.249468                 

   Total energy production (Mtoe)  Total energy consumption (Mtoe)  \
0                      100.112749                        22.188078   
1                      102.586171                        23.469959   
2                      104.205908                        24.024343   
3                      104.928745                        24.110238   
4                      100.612596                        23.239627   

   Share of renewables in electricity production (%)  \
0                                           0.782972   
1                                           1.580793   
2                                           1.022926   
3                                           1.709195   
4                                           0.783869   

   Share of electricity in total final energy consumption (%)  ...  \
0                                           8.376592           ...   
1                                           7.994748           ...   
2                                           8.490068           ...   
3                                           8.291029           ...   
4                                           9.170605           ...   

   Refined oil products production (Mt)  Natural gas production (bcm)  \
0                                25.395                   45.68403547   
1                                25.435                   49.53198889   
2                                25.459                   51.67001137   
3                                25.463                   52.38599054   
4                                23.971                   48.20601995   

  Natural gas domestic consumption (bcm)  \
0                              14.301991   
1                              15.312995   
2                              15.727010   
3                              16.596984   
4                              16.117004   

   Energy intensity of GDP at constant purchasing power parities (koe/$15p)  \
0                                           0.095856                          
1                                           0.102625                          
2                                           0.103192                          
3                                           0.105782                          
4                                           0.102888                          

   Electricity production (TWh)  Electricity domestic consumption (TWh)  \
0                        17.242                                  13.693   
1                        18.535                                  14.058   
2                        19.454                                  15.130   
3                        20.653                                  15.144   
4                        21.177                                  15.545   

   Coal and lignite domestic consumptio

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1364 entries, 0 to 1363
Data columns (total 21 columns):
 #   Column                                                                    Non-Null Count  Dtype  
---  ------                                                                    --------------  -----  
 0   country                                                                   1364 non-null   object 
 1   Year                                                                      1364 non-null   int64  
 2   Region                                                                    1364 non-null   object 
 3   CO2 emissions from fuel combustion (MtCO2)                                1364 non-null   float64
 4   Average CO2 emission factor (tCO2/toe)                                    1364 non-null   float64
 5   CO2 intensity at constant purchasing power parities (kCO2/$15p)           1364 non-null   float64
 6   Total energy production (Mtoe)                                  

In [4]:
df.describe()

Year  CO2 emissions from fuel combustion (MtCO2)  \
count  1364.000000                                 1364.000000   
mean   2005.000000                                  550.375178   
std       8.947552                                 1213.057599   
min    1990.000000                                    7.597759   
25%    1997.000000                                   99.947198   
50%    2005.000000                                  221.036281   
75%    2013.000000                                  423.833152   
max    2020.000000                                 9716.772478   

       Average CO2 emission factor (tCO2/toe)  \
count                             1364.000000   
mean                                 2.238542   
std                                  0.560594   
min                                  0.412331   
25%                                  2.021666   
50%                                  2.339406   
75%                                  2.521811   
max                                  3.516984   

       CO2 intensity at constant purchasing power parities (kCO2/$15p)  \
count                                        1364.000000                 
mean                                            0.339275                 
std                                             0.246502                 
min                                             0.063650                 
25%                                             0.194481                 
50%                                             0.255510                 
75%                                             0.421460                 
max                                             1.820894                 

       Total energy production (Mtoe)  Total energy consumption (Mtoe)  \
count                     1364.000000                      1364.000000   
mean                       229.826912                       225.967632   
std                        400.993541                       445.242818   
min                          2.939712                         2.622633   
25%                         34.720989                        46.632538   
50%                        102.602180                        93.825969   
75%                        217.237230                       195.807818   
max                       2749.046580                      3381.399262   

       Share of renewables in electricity production (%)  \
count                                        1364.000000   
mean                                           24.076995   
std                                            25.490850   
min                                             0.000000   
25%                                             6.097708   
50%                                            14.871924   
75%                                            33.281413   
max                                            99.817877   

       Share of electricity in total final energy consumption (%)  \
count                                        1364.000000            
mean                                           17.622567            
std                                             7.296381            
min                                             0.937144            
25%                                            13.259106            
50%                                            16.869971            
75%                                            21.392581            
max                                            50.011500            

       Oil products domestic consumption (Mt)  \
count                             1364.000000   
mean                                68.848847   
std                                128.339745   
min                                  1.949000   
25%                                 12.809000   
50%                                 27.752179   
75%                                 77.500856   
max                                888.491000   

       Refined oil products production

# Preprocessing

In [5]:
df.isnull().sum()

country                                                                     0
Year                                                                        0
Region                                                                      0
CO2 emissions from fuel combustion (MtCO2)                                  0
Average CO2 emission factor (tCO2/toe)                                      0
CO2 intensity at constant purchasing power parities (kCO2/$15p)             0
Total energy production (Mtoe)                                              0
Total energy consumption (Mtoe)                                             0
Share of renewables in electricity production (%)                           0
Share of electricity in total final energy consumption (%)                  0
Oil products domestic consumption (Mt)                                      0
Refined oil products production (Mt)                                        0
Natural gas production (bcm)                                    

In [6]:
#menghilangkan variabel yang tidak dibutuhkan
df=df.drop(columns=['Share of wind and solar in electricity production (%)'], inplace=False,axis=1)
df=df.drop(columns=['Coal and lignite production (Mt)'], inplace=False,axis=1)
df=df.drop(columns=['Region'], inplace=False,axis=1)
df=df.drop(columns=['Natural gas production (bcm)'], inplace=False,axis=1)
df=df.drop(columns=['Coal and lignite domestic consumption (Mt)'], inplace=False,axis=1)
df=df.drop(columns=['Year'], inplace=False,axis=1)


In [7]:
df

country  CO2 emissions from fuel combustion (MtCO2)  \
0       Algeria                                   52.981921   
1       Algeria                                   57.149971   
2       Algeria                                   57.262430   
3       Algeria                                   59.198702   
4       Algeria                                   56.347927   
...         ...                                         ...   
1359  Venezuela                                  130.244135   
1360  Venezuela                                  124.106123   
1361  Venezuela                                  113.249553   
1362  Venezuela                                  101.200206   
1363  Venezuela                                   85.048356   

      Average CO2 emission factor (tCO2/toe)  \
0                                   2.387855   
1                                   2.435026   
2                                   2.383517   
3                                   2.455335   
4                                   2.424649   
...                                      ...   
1359                                2.214743   
1360                                2.222989   
1361                                2.701646   
1362                                2.793624   
1363                                2.916478   

      CO2 intensity at constant purchasing power parities (kCO2/$15p)  \
0                                              0.228889                 
1                                              0.249895                 
2                                              0.245959                 
3                                              0.259730                 
4                                              0.249468                 
...                                                 ...                 
1359                                           0.304632                 
1360                                           0.344218                 
1361                                           0.390782                 
1362                                           0.537237                 
1363                                           0.601990                 

      Total energy production (Mtoe)  Total energy consumption (Mtoe)  \
0                         100.112749                        22.188078   
1                         102.586171                        23.469959   
2                         104.205908                        24.024343   
3                         104.928745                        24.110238   
4                         100.612596                        23.239627   
...                              ...                              ...   
1359                      169.124743                        58.807791   
1360                      148.976952                        55.828488   
1361                      115.312748                        41.918720   
1362                       81.895069                        36.225425   
1363                       51.397630                        29.161319   

      Share of renewables in electricity production (%)  \
0                                              0.782972   
1                                              1.580793   
2                                              1.022926   
3                                              1.709195   
4                                              0.783869   
...                                                 ...   
1359                                          58.377863   
1360                                          58.379586   
1361                                          58.380532   
1362                                          58.377040   
1363                                          60.944184   

      Share of electricity in total final energy consumption (%)  \
0                                              8.376592            
1                                              7.994748            
2      

In [8]:
#menghitung jumlah output
df['country'].value_counts().sort_values(ascending = False)

Algeria                 31
Argentina               31
Egypt                   31
Australia               31
Belgium                 31
Brazil                  31
Canada                  31
Chile                   31
China                   31
Colombia                31
Czechia                 31
France                  31
Malaysia                31
Germany                 31
India                   31
Indonesia               31
Iran                    31
Italy                   31
Japan                   31
Kazakhstan              31
Kuwait                  31
Mexico                  31
Netherlands             31
New Zealand             31
South Korea             31
Nigeria                 31
Norway                  31
Poland                  31
Portugal                31
Romania                 31
Russia                  31
Saudi Arabia            31
South Africa            31
Spain                   31
Uzbekistan              31
Sweden                  31
Taiwan                  31
T

In [9]:
#melabelkan data output
df[['country']] = df[['country']].apply(LabelEncoder().fit_transform)

#view udpated DataFrame
print(df)

      country  CO2 emissions from fuel combustion (MtCO2)  \
0           0                                   52.981921   
1           0                                   57.149971   
2           0                                   57.262430   
3           0                                   59.198702   
4           0                                   56.347927   
...       ...                                         ...   
1359       43                                  130.244135   
1360       43                                  124.106123   
1361       43                                  113.249553   
1362       43                                  101.200206   
1363       43                                   85.048356   

      Average CO2 emission factor (tCO2/toe)  \
0                                   2.387855   
1                                   2.435026   
2                                   2.383517   
3                                   2.455335   
4                          

In [10]:
#menghitung jumlah output
df['country'].value_counts().sort_values(ascending = False)

0     31
1     31
10    31
2     31
3     31
4     31
5     31
6     31
7     31
8     31
9     31
11    31
20    31
12    31
13    31
14    31
15    31
16    31
17    31
18    31
19    31
21    31
22    31
23    31
32    31
24    31
25    31
26    31
27    31
28    31
29    31
30    31
31    31
33    31
42    31
34    31
35    31
36    31
37    31
38    31
39    31
40    31
41    31
43    31
Name: country, dtype: int64

In [11]:
#feature selection data and split data
X = df.drop(columns='country')
y = df['country']

In [12]:
#data traing 90% dan data testing 10% before random oversampling
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=200)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1227, 14), (137, 14), (1227,), (137,))

In [14]:
#Transformasi/normalisasi data dengan MinMax before resampling
columns = ['CO2 emissions from fuel combustion (MtCO2)', 'Average CO2 emission factor (tCO2/toe)', 'CO2 intensity at constant purchasing power parities (kCO2/$15p)', 'Total energy production (Mtoe)', 'Total energy consumption (Mtoe)', 'Share of renewables in electricity production (%)', 'Share of electricity in total final energy consumption (%)']
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train[columns])
X_test_scale = scaler.transform(X_test[columns])

In [15]:
X_train[columns]=X_train_scale
X_test[columns]=X_test_scale

# RFC

In [16]:
seed=123
np.random.seed(seed)

In [17]:
rfc_100 = RandomForestClassifier()

# fit the model to the training set

rfc_100.fit(X_train, y_train)

# Predict on the test set results

y_pred_100 = rfc_100.predict(X_test)

In [18]:
# Check accuracy score 
print('Model accuracy score with 100 random forest : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

Model accuracy score with 100 random forest : 1.0000


In [19]:
cm = confusion_matrix(y_test, y_pred_100)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[1 0 0 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 4]]


In [20]:
print ('accuracy_score: ',accuracy_score(y_test, y_pred_100))
print ('f1_score: ',f1_score(y_test, y_pred_100, pos_label='positive', average='micro'))
print ('recall_score: ',recall_score(y_test, y_pred_100, pos_label='positive', average='micro'))
print ('precision_score: ',precision_score(y_test, y_pred_100, pos_label='positive', average='micro'))

accuracy_score:  1.0
f1_score:  1.0
recall_score:  1.0
precision_score:  1.0


# Simpan Model

In [21]:
fillname1="RFC_model1.pkl"
pickle.dump(rfc_100, open(fillname1,"wb"))

In [22]:
fillname11="RFC_model1.sav"
pickle.dump(rfc_100, open(fillname11,"wb"))

In [23]:
fillname5="scaler.pkl"
pickle.dump(scaler, open(fillname5,"wb"))

In [71]:
import pandas as pd
Data = pd.read_csv('Crime_Data_from_2020_to_Present.csv')

In [27]:
import pandas as pd
pd.show_versions(as_json=False)


INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_Indonesia.1252

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2023.2
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.11.0
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli      

In [70]:
#menghilangkan variabel yang tidak dibutuhkan
Data=Data.drop(columns=['Date Rptd'], inplace=False,axis=1)
Data=Data.drop(columns=['AREA'], inplace=False,axis=1)
Data=Data.drop(columns=['DATE OCC'], inplace=False,axis=1)
Data=Data.drop(columns=['DR_NO'], inplace=False,axis=1)
Data=Data.drop(columns=['Crm Cd Desc'], inplace=False,axis=1)
Data=Data.drop(columns=['Mocodes'], inplace=False,axis=1)
Data=Data.drop(columns=['Vict Sex'], inplace=False,axis=1)
Data=Data.drop(columns=['Vict Descent'], inplace=False,axis=1)
Data=Data.drop(columns=['Premis Cd'], inplace=False,axis=1)
Data=Data.drop(columns=['Premis Desc'], inplace=False,axis=1)
Data=Data.drop(columns=['Status'], inplace=False,axis=1)
Data=Data.drop(columns=['Status Desc'], inplace=False,axis=1)
Data=Data.drop(columns=['LOCATION'], inplace=False,axis=1)
Data=Data.drop(columns=['Cross Street'], inplace=False,axis=1)
Data=Data.drop(columns=['LAT'], inplace=False,axis=1)
Data=Data.drop(columns=['LON'], inplace=False,axis=1)
Data=Data.drop(columns=['Weapon Desc'], inplace=False,axis=1)
Data=Data.drop(columns=['Crm Cd 1'], inplace=False,axis=1)
Data=Data.drop(columns=['Crm Cd 2'], inplace=False,axis=1)
Data=Data.drop(columns=['Crm Cd 3'], inplace=False,axis=1)
Data=Data.drop(columns=['Crm Cd 4'], inplace=False,axis=1)
Data=Data.drop(columns=['Weapon Used Cd'], inplace=False,axis=1)

In [67]:
Data=Data.drop(columns=['Part 1-2'], inplace=False,axis=1)

In [73]:
fillname12="Data_Set1.sav"
pickle.dump(Data, open(fillname12,"wb"))

In [28]:
!pip install streamlit-option-menu